# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resource/pump_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddPumpDialog(object):
    def setupUi(self, AddPumpDialog):
        AddPumpDialog.setObjectName("AddPumpDialog")
        AddPumpDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddPumpDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_name = QtWidgets.QLabel(AddPumpDialog)
        self.label_name.setObjectName("label_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_name)
        self.lineEdit_name = QtWidgets.QLineEdit(AddPumpDialog)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_name)
        self.label_flow = QtWidgets.QLabel(AddPumpDialog)
        self.label_flow.setObjectName("label_flow")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_flow)
        self.lineEdit_flow = QtWidgets.QLineEdit(AddPumpDialog)
        self.lineEdit_flow.setObjectName("lineEdit_flow")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_flow)
        self.label_current = QtWidgets.QLabel(AddPumpDialog)
        self.label_current.setObjectName("label_current")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_current)
        self.horizontalLayout_current = QtWidgets.QHBoxLayout()
        self.horizontalLayout_current.setObjectName("horizontalLayout_current")
        self.spinBox_current_min = QtWidgets.QSpinBox(AddPumpDialog)
        self.spinBox_current_min.setProperty("value", 0)
        self.spinBox_current_min.setObjectName("spinBox_current_min")
        self.horizontalLayout_current.addWidget(self.spinBox_current_min)
        self.label_current_separator = QtWidgets.QLabel(AddPumpDialog)
        self.label_current_separator.setObjectName("label_current_separator")
        self.horizontalLayout_current.addWidget(self.label_current_separator)
        self.spinBox_current_max = QtWidgets.QSpinBox(AddPumpDialog)
        self.spinBox_current_max.setProperty("value", 60)
        self.spinBox_current_max.setObjectName("spinBox_current_max")
        self.horizontalLayout_current.addWidget(self.spinBox_current_max)
        self.label_current_unit = QtWidgets.QLabel(AddPumpDialog)
        self.label_current_unit.setObjectName("label_current_unit")
        self.horizontalLayout_current.addWidget(self.label_current_unit)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_current)
        self.label_power = QtWidgets.QLabel(AddPumpDialog)
        self.label_power.setObjectName("label_power")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_power)
        self.horizontalLayout_power = QtWidgets.QHBoxLayout()
        self.horizontalLayout_power.setObjectName("horizontalLayout_power")
        self.lineEdit_power = QtWidgets.QLineEdit(AddPumpDialog)
        self.lineEdit_power.setObjectName("lineEdit_power")
        self.horizontalLayout_power.addWidget(self.lineEdit_power)
        self.label_power_unit = QtWidgets.QLabel(AddPumpDialog)
        self.label_power_unit.setObjectName("label_power_unit")
        self.horizontalLayout_power.addWidget(self.label_power_unit)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_power)
        self.label_head = QtWidgets.QLabel(AddPumpDialog)
        self.label_head.setObjectName("label_head")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_head)
        self.horizontalLayout_head = QtWidgets.QHBoxLayout()
        self.horizontalLayout_head.setObjectName("horizontalLayout_head")
        self.lineEdit_head = QtWidgets.QLineEdit(AddPumpDialog)
        self.lineEdit_head.setObjectName("lineEdit_head")
        self.horizontalLayout_head.addWidget(self.lineEdit_head)
        self.label_head_unit = QtWidgets.QLabel(AddPumpDialog)
        self.label_head_unit.setObjectName("label_head_unit")
        self.horizontalLayout_head.addWidget(self.label_head_unit)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_head)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_buttons.setObjectName("horizontalLayout_buttons")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_buttons.addItem(spacerItem)
        self.pushButton_cancel = QtWidgets.QPushButton(AddPumpDialog)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_buttons.addWidget(self.pushButton_cancel)
        self.pushButton_confirm = QtWidgets.QPushButton(AddPumpDialog)
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.horizontalLayout_buttons.addWidget(self.pushButton_confirm)
        self.verticalLayout.addLayout(self.horizontalLayout_buttons)

        self.retranslateUi(AddPumpDialog)
        QtCore.QMetaObject.connectSlotsByName(AddPumpDialog)

    def retranslateUi(self, AddPumpDialog):
        _translate = QtCore.QCoreApplication.translate
        AddPumpDialog.setWindowTitle(_translate("AddPumpDialog", "添加循环泵"))
        self.label_name.setText(_translate("AddPumpDialog", "泵名称："))
        self.label_flow.setText(_translate("AddPumpDialog", "循环量："))
        self.label_current.setText(_translate("AddPumpDialog", "电流范围："))
        self.label_current_separator.setText(_translate("AddPumpDialog", "~"))
        self.label_current_unit.setText(_translate("AddPumpDialog", "A"))
        self.label_power.setText(_translate("AddPumpDialog", "功率："))
        self.label_power_unit.setText(_translate("AddPumpDialog", "KW"))
        self.label_head.setText(_translate("AddPumpDialog", "扬程："))
        self.label_head_unit.setText(_translate("AddPumpDialog", "m/s"))
        self.pushButton_cancel.setText(_translate("AddPumpDialog", "取消"))
        self.pushButton_confirm.setText(_translate("AddPumpDialog", "确定"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddPumpDialog = QtWidgets.QDialog()
    ui = Ui_AddPumpDialog()
    ui.setupUi(AddPumpDialog)
    AddPumpDialog.show()
    sys.exit(app.exec_())
